---
- name: Install Access Point Packages
  apt:
    name: "{{ packages }}"

- name: Safety First!
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ packages }}"

